# Generated by Django 3.1.7 on 2021-06-14 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Notes', '0001_initial'),
        ('Videos', '0001_initial'),
        ('Sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GroupCreator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='GroupMembers', to=settings.AUTH_USER_MODEL)),
                ('notes', models.ManyToManyField(blank=True, related_name='GroupNotes', to='Notes.Notes')),
                ('sites', models.ManyToManyField(blank=True, related_name='GroupSites', to='Sites.Sites')),
                ('videos', models.ManyToManyField(blank=True, related_name='GroupVideos', to='Videos.Videos')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('copied_notes', models.ManyToManyField(blank=True, related_name='Notes', to='Notes.Notes')),
                ('groups', models.ManyToManyField(blank=True, related_name='UserGroups', to='Profile.Groups')),
                ('saved_sites', models.ManyToManyField(blank=True, related_name='Sites', to='Sites.Sites')),
                ('saved_videos', models.ManyToManyField(blank=True, related_name='Videos', to='Videos.Videos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.groups')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='GroupCommentUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
