# Generated by Django 3.1.7 on 2021-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
        ('Sites', '0001_initial'),
        ('Notes', '0002_article_sitenotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ManyToManyField(blank=True, to='Sites.Sites'),
        ),
        migrations.AddField(
            model_name='article',
            name='videos',
            field=models.ManyToManyField(blank=True, to='Videos.Videos'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
