# Generated by Django 3.1.7 on 2021-07-27 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0003_auto_20210727_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotesComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('site_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Notes.sitenotes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SiteNotesComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
